### ISSUE TITLE
Create Check_mk plugin for ercole events

### ISSUE THREAD

**Issue by capaaway** [ercole-io/ercole-server#28]
Create an Ercole plugin in order to monitor ercole event.
The plugin must be customizable to show different level of events.

**Comment by amreo** [comment]
For which software should the plugin be developed?

**Comment by raffaelloferrari** [comment]
First release:
![Ercole-alarm](https://user-images.githubusercontent.com/47225245/66144699-9fb45300-e609-11e9-9d30-c80b8969ed4f.PNG)
