### ISSUE TITLE
Add username and password to demo.ercole.io login 

### ISSUE THREAD

**Issue by raffaelloferrari** [ercole-io/ercole-server#57]
In case the server is a demo show the possibility to see username and password

**Comment by amreo** [comment]
I'm too lazy and I don't want to add a options for showing the credentials. Use this command to trasform a "normal" jar to a demo jar.
`
unzip ercole-server-latest.jar "BOOT-INF/classes/templates/auth/login.html"
cat << EOF | patch BOOT-INF/classes/templates/auth/login.html 
39a40,42
>                                                 <div class="alert alert-success">
>                                                         The username is "user", the password is "password"
>                                                 </div>
61c64
< </html>
\ No newline at end of file
---
> </html>
EOF
jar -uf ercole-server-latest.jar BOOT-INF/classes/templates/auth/login.html
`
